# Form implementation generated from reading ui file 'c:\Users\ds_sa\Desktop\Fall 23\Database\Project\additemtomenu.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(513, 508)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ItemID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ItemID.setGeometry(QtCore.QRect(100, 10, 113, 22))
        self.ItemID.setObjectName("ItemID")
        self.ItemName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ItemName.setGeometry(QtCore.QRect(100, 50, 113, 22))
        self.ItemName.setObjectName("ItemName")
        self.ItemPrice = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ItemPrice.setGeometry(QtCore.QRect(100, 90, 113, 22))
        self.ItemPrice.setObjectName("ItemPrice")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 121, 16))
        self.label_3.setObjectName("label_3")
        self.ItemDescription = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.ItemDescription.setGeometry(QtCore.QRect(323, 10, 171, 87))
        self.ItemDescription.setObjectName("ItemDescription")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 10, 121, 16))
        self.label_5.setObjectName("label_5")
        self.ItemIngredients = QtWidgets.QListWidget(parent=self.centralwidget)
        self.ItemIngredients.setGeometry(QtCore.QRect(100, 190, 256, 192))
        self.ItemIngredients.setObjectName("ItemIngredients")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 190, 121, 16))
        self.label_6.setObjectName("label_6")
        self.addItemBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addItemBtn.setGeometry(QtCore.QRect(380, 400, 93, 28))
        self.addItemBtn.setObjectName("addItemBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 513, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Item ID"))
        self.label_2.setText(_translate("MainWindow", "Item Name"))
        self.label_3.setText(_translate("MainWindow", "Price"))
        self.label_5.setText(_translate("MainWindow", "Description"))
        self.label_6.setText(_translate("MainWindow", "Ingredients"))
        self.addItemBtn.setText(_translate("MainWindow", "Add Item"))
