# Form implementation generated from reading ui file 'c:\Users\ds_sa\Desktop\Fall 23\Database\Project\AdminHome.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(358, 373)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.AddtoItems = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AddtoItems.setGeometry(QtCore.QRect(32, 100, 141, 28))
        self.AddtoItems.setObjectName("AddtoItems")
        self.DeleteItem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DeleteItem.setGeometry(QtCore.QRect(190, 210, 141, 28))
        self.DeleteItem.setObjectName("DeleteItem")
        self.ViewInventory = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ViewInventory.setGeometry(QtCore.QRect(32, 160, 141, 28))
        self.ViewInventory.setObjectName("ViewInventory")
        self.ManageInventory = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ManageInventory.setGeometry(QtCore.QRect(190, 160, 141, 28))
        self.ManageInventory.setObjectName("ManageInventory")
        self.ViewOrders = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ViewOrders.setGeometry(QtCore.QRect(30, 260, 301, 28))
        self.ViewOrders.setObjectName("ViewOrders")
        self.AddtoMenu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AddtoMenu.setGeometry(QtCore.QRect(30, 210, 141, 28))
        self.AddtoMenu.setObjectName("AddtoMenu")
        self.DeleteItemFromItems = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DeleteItemFromItems.setGeometry(QtCore.QRect(190, 100, 141, 28))
        self.DeleteItemFromItems.setObjectName("DeleteItemFromItems")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 358, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Admin Homepage"))
        self.AddtoItems.setText(_translate("MainWindow", "Add Item"))
        self.DeleteItem.setText(_translate("MainWindow", "Remove From Menu"))
        self.ViewInventory.setText(_translate("MainWindow", "View Inventory"))
        self.ManageInventory.setText(_translate("MainWindow", "Manage Inventory"))
        self.ViewOrders.setText(_translate("MainWindow", "View Orders"))
        self.AddtoMenu.setText(_translate("MainWindow", "Add To Menu"))
        self.DeleteItemFromItems.setText(_translate("MainWindow", "Delete Item"))
