# Form implementation generated from reading ui file 'c:\Users\ds_sa\Desktop\Fall 23\Database\Project\Cafeteria Menu Form.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(437, 574)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 381, 71))
        self.groupBox.setObjectName("groupBox")
        self.TapalCafeteria = QtWidgets.QRadioButton(parent=self.groupBox)
        self.TapalCafeteria.setGeometry(QtCore.QRect(10, 30, 171, 20))
        self.TapalCafeteria.setObjectName("TapalCafeteria")
        self.Cafe2Go = QtWidgets.QRadioButton(parent=self.groupBox)
        self.Cafe2Go.setGeometry(QtCore.QRect(200, 30, 171, 20))
        self.Cafe2Go.setObjectName("Cafe2Go")
        self.Menu = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.Menu.setGeometry(QtCore.QRect(30, 180, 381, 281))
        self.Menu.setObjectName("Menu")
        self.Menu.setColumnCount(3)
        self.Menu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Menu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Menu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Menu.setHorizontalHeaderItem(2, item)
        self.GoToCart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.GoToCart.setGeometry(QtCore.QRect(290, 490, 121, 28))
        self.GoToCart.setObjectName("GoToCart")
        self.SelectCafeteria = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SelectCafeteria.setGeometry(QtCore.QRect(290, 110, 121, 28))
        self.SelectCafeteria.setObjectName("SelectCafeteria")
        self.MyOrders = QtWidgets.QPushButton(parent=self.centralwidget)
        self.MyOrders.setGeometry(QtCore.QRect(30, 490, 121, 28))
        self.MyOrders.setObjectName("MyOrders")
        self.ViewItem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ViewItem.setGeometry(QtCore.QRect(160, 490, 121, 28))
        self.ViewItem.setObjectName("ViewItem")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 437, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Choose Cafeteria"))
        self.TapalCafeteria.setText(_translate("MainWindow", "Tapal (Lower Ground)"))
        self.Cafe2Go.setText(_translate("MainWindow", "Cafe2Go (Ground Floor)"))
        item = self.Menu.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Item Name"))
        item = self.Menu.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cafeteria"))
        item = self.Menu.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price (Rs.)"))
        self.GoToCart.setText(_translate("MainWindow", "Go to Cart"))
        self.SelectCafeteria.setText(_translate("MainWindow", "Select Cafeteria"))
        self.MyOrders.setText(_translate("MainWindow", "My Orders"))
        self.ViewItem.setText(_translate("MainWindow", "View Item Details"))
