# Form implementation generated from reading ui file 'c:\Users\ds_sa\Desktop\Fall 23\Database\Project\Cart Form.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(659, 388)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 230, 111, 16))
        self.label.setObjectName("label")
        self.TotalBill = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.TotalBill.setGeometry(QtCore.QRect(530, 230, 111, 22))
        self.TotalBill.setObjectName("TotalBill")
        self.PlaceOrder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PlaceOrder.setGeometry(QtCore.QRect(520, 290, 121, 28))
        self.PlaceOrder.setObjectName("PlaceOrder")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 230, 111, 16))
        self.label_2.setObjectName("label_2")
        self.OrderInstructions = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.OrderInstructions.setGeometry(QtCore.QRect(90, 230, 251, 87))
        self.OrderInstructions.setObjectName("OrderInstructions")
        self.CartTable = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.CartTable.setGeometry(QtCore.QRect(10, 20, 631, 192))
        self.CartTable.setObjectName("CartTable")
        self.CartTable.setColumnCount(5)
        self.CartTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.CartTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CartTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CartTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CartTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.CartTable.setHorizontalHeaderItem(4, item)
        self.ClearCart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ClearCart.setGeometry(QtCore.QRect(370, 290, 121, 28))
        self.ClearCart.setObjectName("ClearCart")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 659, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Total:"))
        self.PlaceOrder.setText(_translate("MainWindow", "Place Order"))
        self.label_2.setText(_translate("MainWindow", "Instructions:"))
        item = self.CartTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Item"))
        item = self.CartTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cafe"))
        item = self.CartTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price"))
        item = self.CartTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.CartTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total"))
        self.ClearCart.setText(_translate("MainWindow", "Clear Cart"))
