# Form implementation generated from reading ui file 'c:\Users\ds_sa\Desktop\Fall 23\Database\Project\deleteitemfrommenu.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(386, 192)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 61))
        self.label.setObjectName("label")
        self.DeleteItem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DeleteItem.setGeometry(QtCore.QRect(150, 110, 93, 28))
        self.DeleteItem.setObjectName("DeleteItem")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 101, 61))
        self.label_2.setObjectName("label_2")
        self.CafeName = QtWidgets.QComboBox(parent=self.centralwidget)
        self.CafeName.setGeometry(QtCore.QRect(130, 70, 151, 22))
        self.CafeName.setObjectName("CafeName")
        self.CafeName.addItem("")
        self.CafeName.addItem("")
        self.ItemID = QtWidgets.QComboBox(parent=self.centralwidget)
        self.ItemID.setGeometry(QtCore.QRect(130, 30, 171, 22))
        self.ItemID.setObjectName("ItemID")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 386, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enter Item ID"))
        self.DeleteItem.setText(_translate("MainWindow", "Delete"))
        self.label_2.setText(_translate("MainWindow", "Enter Cafe Name"))
        self.CafeName.setItemText(0, _translate("MainWindow", "Tapal Cafeteria"))
        self.CafeName.setItemText(1, _translate("MainWindow", "Cafe2Go"))
