# Form implementation generated from reading ui file 'c:\Users\ds_sa\Desktop\Fall 23\Database\Project\updateinventory.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(293, 273)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 121, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 121, 31))
        self.label_3.setObjectName("label_3")
        self.NewPrice = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.NewPrice.setGeometry(QtCore.QRect(130, 60, 113, 22))
        self.NewPrice.setObjectName("NewPrice")
        self.NewQuantity = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.NewQuantity.setGeometry(QtCore.QRect(130, 100, 113, 22))
        self.NewQuantity.setObjectName("NewQuantity")
        self.Update = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Update.setGeometry(QtCore.QRect(160, 150, 93, 28))
        self.Update.setObjectName("Update")
        self.IngredientID = QtWidgets.QComboBox(parent=self.centralwidget)
        self.IngredientID.setGeometry(QtCore.QRect(130, 20, 121, 22))
        self.IngredientID.setObjectName("IngredientID")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 293, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enter Ingredient ID"))
        self.label_2.setText(_translate("MainWindow", "Enter New Price"))
        self.label_3.setText(_translate("MainWindow", "Enter New Quantity"))
        self.Update.setText(_translate("MainWindow", "Update"))
