# Form implementation generated from reading ui file 'c:\Users\ds_sa\Desktop\Fall 23\Database\Project\View Item Form.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 381)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 101, 16))
        self.label_3.setObjectName("label_3")
        self.ItemPrice = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ItemPrice.setGeometry(QtCore.QRect(120, 120, 291, 22))
        self.ItemPrice.setObjectName("ItemPrice")
        self.AddToCart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AddToCart.setGeometry(QtCore.QRect(330, 290, 111, 28))
        self.AddToCart.setObjectName("AddToCart")
        self.BackToMenu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BackToMenu.setGeometry(QtCore.QRect(40, 290, 93, 28))
        self.BackToMenu.setObjectName("BackToMenu")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 160, 101, 16))
        self.label_5.setObjectName("label_5")
        self.ItemQuantity = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.ItemQuantity.setGeometry(QtCore.QRect(120, 240, 42, 22))
        self.ItemQuantity.setObjectName("ItemQuantity")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 240, 61, 16))
        self.label_6.setObjectName("label_6")
        self.ItemRecipe = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ItemRecipe.setGeometry(QtCore.QRect(350, 240, 93, 28))
        self.ItemRecipe.setObjectName("ItemRecipe")
        self.ItemSelector = QtWidgets.QComboBox(parent=self.centralwidget)
        self.ItemSelector.setGeometry(QtCore.QRect(120, 80, 291, 22))
        self.ItemSelector.setObjectName("ItemSelector")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 80, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 40, 81, 16))
        self.label_8.setObjectName("label_8")
        self.CafeSelector = QtWidgets.QComboBox(parent=self.centralwidget)
        self.CafeSelector.setGeometry(QtCore.QRect(120, 40, 291, 22))
        self.CafeSelector.setObjectName("CafeSelector")
        self.ItemDescription = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ItemDescription.setGeometry(QtCore.QRect(120, 160, 291, 22))
        self.ItemDescription.setObjectName("ItemDescription")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Price:"))
        self.AddToCart.setText(_translate("MainWindow", "Add to Cart"))
        self.BackToMenu.setText(_translate("MainWindow", "Back to Menu"))
        self.label_5.setText(_translate("MainWindow", "Description:"))
        self.label_6.setText(_translate("MainWindow", "Quantity:"))
        self.ItemRecipe.setText(_translate("MainWindow", "Recipe"))
        self.label_7.setText(_translate("MainWindow", "Select Item:"))
        self.label_8.setText(_translate("MainWindow", "Select Cafe:"))
